---
- name: Asegurar que la línea específica esté comentada en slurm.conf
  hosts: all
  become: yes
  vars:
    linea_deseada: "PartitionName=interactive Nodes=bioinf3.vhio.org,bioinf4.vhio.org,bioinf6.vhio.org MaxTime=INFINITE State=UP PriorityTier=50"
    
  tasks:
    - name: Verificar existencia de slurm.conf
      stat:
        path: /etc/slurm/slurm.conf
      register: slurm_conf
    
    - name: Buscar cualquier versión de la línea (comentada o no)
      shell: |
        grep -F "{{ linea_deseada }}" /etc/slurm/slurm.conf || echo "no_existe"
      register: linea_actual
      changed_when: false
      when: slurm_conf.stat.exists
    
    - name: Mostrar estado actual de la línea
      debug:
        var: linea_actual.stdout_lines
      when: slurm_conf.stat.exists
    
    - name: Añadir línea comentada (si no existe en ninguna forma)
      lineinfile:
        path: /etc/slurm/slurm.conf
        line: "# {{ linea_deseada }}"
        state: present
      when: 
        - slurm_conf.stat.exists
        - "'no_existe' in linea_actual.stdout"
    
    - name: Comentar línea si existe sin comentar
      replace:
        path: /etc/slurm/slurm.conf
        regexp: "^{{ linea_deseada }}$"
        replace: "# {{ linea_deseada }}"
      when: 
        - slurm_conf.stat.exists
        - "'{{ linea_deseada }}' in linea_actual.stdout"
    
    - name: Mostrar resumen final
      debug:
        msg: |
          ===== RESUMEN FINAL =====
          Archivo slurm.conf existe: {{ slurm_conf.stat.exists }}
          Estado línea:
            - Ya existía comentada: {{ '# ' + linea_deseada in linea_actual.stdout_lines }}
            - Existía sin comentar: {{ linea_deseada in linea_actual.stdout_lines }}
            - No existía: {{ 'no_existe' in linea_actual.stdout }}
          
          Acciones realizadas:
            - Línea añadida como comentario: {{ '# ' + linea_deseada in linea_actual.stdout_lines and 'no_existe' in linea_actual.stdout }}
            - Línea comentada: {{ linea_deseada in linea_actual.stdout_lines }}
            - Sin cambios necesarios: {{ '# ' + linea_deseada in linea_actual.stdout_lines }}
