---
- name: Actualizar nodos en partición de slurm.conf
  hosts: all
  become: yes
  vars:
    partition_name: "interactive"  # Nombre de la partición a modificar
    nuevos_nodos: ["bioinf3.vhio.org", "bioinf4.vhio.org", "bioinf5.vhio.org", "bioinf6.vhio.org", "bioinf7.vhio.org"]  # Lista COMPLETA de nodos deseada

  tasks:
    - name: Verificar existencia del archivo
      stat:
        path: /etc/slurm/slurm.conf
      register: slurm_conf

    - name: Actualizar lista de nodos (versión activa)
      replace:
        path: /etc/slurm/slurm.conf
        regexp: '^(PartitionName={{ partition_name }}.*Nodes=)[^ ]+'
        replace: '\1{{ nuevos_nodos | join(",") }}'
        backrefs: yes
      register: cambio_activo
      when: slurm_conf.stat.exists

    - name: Actualizar lista de nodos (versión comentada)
      replace:
        path: /etc/slurm/slurm.conf
        regexp: '^(#\s*PartitionName={{ partition_name }}.*Nodes=)[^ ]+'
        replace: '\1{{ nuevos_nodos | join(",") }}'
        backrefs: yes
      register: cambio_comentado
      when: slurm_conf.stat.exists

    - name: Verificar cambios
      shell: |
        grep -A2 "PartitionName={{ partition_name }}" /etc/slurm/slurm.conf || echo "No encontrado"
      register: verificacion
      changed_when: false
      when: slurm_conf.stat.exists

    - name: Mostrar resultado
      debug:
        msg: |-
          === RESULTADO EN {{ inventory_hostname }} ===
          {% if cambio_activo is defined and cambio_activo.changed %}
          - Se actualizó la versión ACTIVA de la partición
          {% elif cambio_comentado is defined and cambio_comentado.changed %}
          - Se actualizó solo la versión COMENTADA
          {% else %}
          - No se realizaron cambios (¿La partición existe?)
          {% endif %}
          Configuración actual:
          {{ verificacion.stdout if verificacion is defined else "Archivo no encontrado" }}
