---
- name: Actualizar correctamente nodos en la partición interactive
  hosts: all
  become: yes
  vars:
    linea_base: "PartitionName=interactive Nodes=bioinf3.vhio.org,bioinf4.vhio.org,bioinf6.vhio.org"
    nuevo_nodo: "bioinf5.vhio.org"
    
  tasks:
    - name: Verificar existencia de slurm.conf
      stat:
        path: /etc/slurm/slurm.conf
      register: slurm_conf
    
    - name: Buscar línea de la partición interactive (comentada o no)
      shell: |
        grep -P "(^#\s*)?{{ linea_base | regex_escape() }}" /etc/slurm/slurm.conf || echo "no_existe"
      register: linea_actual
      changed_when: false
      when: slurm_conf.stat.exists
    
    - name: Crear nueva línea correctamente formateada
      set_fact:
        nueva_linea: "{{ (linea_actual.stdout is match('^#')) | ternary('# ','') }}{{ linea_base }},{{ nuevo_nodo }} MaxTime=INFINITE State=UP PriorityTier=50"
      when: 
        - slurm_conf.stat.exists
        - "'no_existe' not in linea_actual.stdout"
    
    - name: Reemplazar línea existente
      replace:
        path: /etc/slurm/slurm.conf
        regexp: "{{ linea_actual.stdout | regex_escape() }}"
        replace: "{{ nueva_linea }}"
      when: 
        - slurm_conf.stat.exists
        - "'no_existe' not in linea_actual.stdout"
        - nueva_linea is defined
      register: cambio_realizado
    
    - name: Mostrar resumen claro de cambios
      debug:
        msg: |-
          ===== CAMBIOS REALIZADOS =====
          Línea original encontrada: {{ linea_actual.stdout }}
          Nueva línea configurada: {{ nueva_linea }}
          Nodo añadido: {{ nuevo_nodo }}
          
          NOTA: Servicios no reiniciados.
          Verificar cambios antes de reiniciar.
      when: slurm_conf.stat.exists
    
    - name: Eliminar líneas duplicadas comentadas incorrectas
      lineinfile:
        path: /etc/slurm/slurm.conf
        state: absent
        regexp: "^#.*{{ linea_base | regex_escape() }}"
      when: 
        - slurm_conf.stat.exists
        - cambio_realizado is defined
        - cambio_realizado.changed
