---
- name: Actualizar Nextflow en nodos donde existe
  hosts: all
  gather_facts: no
  
  tasks:
    # 1. CARGAR CREDENCIALES DESDE VAULT
    - name: Cargar vault manualmente
      include_vars:
        file: vault.yml
        name: loaded_vars

    - name: Acceder a las credenciales
      set_fact:
        bioinf_credentials: "{{ loaded_vars.bioinf_credentials }}"

    - name: Extraer IP para buscar en vault
      set_fact:
        host_ip: "{{ inventory_hostname.split(' - ')[1] }}"

    - name: Configurar credenciales para este host
      set_fact:
        ansible_user: "{{ bioinf_credentials[host_ip].user }}"
        ansible_ssh_pass: "{{ bioinf_credentials[host_ip].password }}"
        ansible_become_pass: "{{ bioinf_credentials[host_ip].password }}"

    # 2. VERIFICAR SI NEXTFLOW EXISTE
    - name: Comprobar si nextflow est谩 instalado
      stat:
        path: /usr/local/bin/nextflow
      register: nextflow_exists
      become: yes

    # 3. VERIFICAR VERSIN ACTUAL ANTES
    - name: Obtener versi贸n actual de nextflow
      command: nextflow -version
      register: nextflow_version_before
      ignore_errors: yes
      become: yes
      changed_when: false
      when: nextflow_exists.stat.exists

    # 4. ACTUALIZAR NEXTFLOW
    - name: Ejecutar nextflow self-update
      command: nextflow self-update
      register: update_result
      ignore_errors: yes
      become: yes
      when: nextflow_exists.stat.exists

    # 5. APLICAR PERMISOS 777
    - name: Aplicar permisos 777 al binario de nextflow
      file:
        path: /usr/local/bin/nextflow
        mode: '0777'
        state: file
      become: yes
      when: nextflow_exists.stat.exists

    # 6. VERIFICAR VERSIN DESPUS
    - name: Obtener versi贸n despu茅s de actualizar
      command: nextflow -version
      register: nextflow_version_after
      ignore_errors: yes
      become: yes
      changed_when: false
      when: nextflow_exists.stat.exists

    # 7. LIMPIAR SALIDAS Y MOSTRAR RESULTADOS
    - name: Limpiar las salidas de nextflow
      set_fact:
        clean_before: "{{ nextflow_version_before.stdout | regex_replace('[\\r\\u001b\\[K]', '') | trim | default('N/A') }}"
        clean_after: "{{ nextflow_version_after.stdout | regex_replace('[\\r\\u001b\\[K]', '') | trim | default('N/A') }}"
        clean_update: "{{ update_result.stdout | regex_replace('[\\r\\u001b\\[K]', '') | trim | default('N/A') }}"
      when: nextflow_exists.stat.exists

    - name: Mostrar resumen limpio
      debug:
        msg: |
          {{ inventory_hostname }}:
           Nextflow instalado: {{ 'S' if nextflow_exists.stat.exists else 'NO' }}
           Actualizaci贸n: {{ 'Intentada' if nextflow_exists.stat.exists else 'Saltada' }}
           Versi贸n antes: {{ clean_before | default('N/A') }}
           Versi贸n despu茅s: {{ clean_after | default('N/A') }}
           Permisos: {{ 'Aplicados' if nextflow_exists.stat.exists else 'No aplicados' }}
          憋  Resultado update: {{ clean_update | default('N/A') }}
