---
- name: Test conexión EXTRA SEGURO
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Verificar espacio en /mnt/bioinfnas2/sarcoma
      shell: df -h /mnt/bioinfnas2/sarcoma | tail -1
      register: sarcoma_space
      changed_when: false

    - name: Mostrar espacio disponible
      debug:
        msg: "Espacio en sarcoma: {{ sarcoma_space.stdout }}"

    - name: Crear directorio temporal con nombre único
      raw: |
        mkdir -p /mnt/bioinfnas2/sarcoma/ansible_test_{{ ansible_date_time.epoch }}
        chmod 700 /mnt/bioinfnas2/sarcoma/ansible_test_{{ ansible_date_time.epoch }}
      changed_when: false

    - name: Probar conexión
      ansible.builtin.ping:
      environment:
        TMPDIR: /mnt/bioinfnas2/sarcoma/ansible_test_{{ ansible_date_time.epoch }}

    - name: Limpieza garantizada
      raw: rm -rf /mnt/bioinfnas2/sarcoma/ansible_test_{{ ansible_date_time.epoch }}
      changed_when: false
