# test_vault.yml
---
- name: Test conexión con vault
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Cargar vault manualmente
      include_vars:
        file: vault.yml
        name: bioinf_credentials

    - name: Debug 1 - Mostrar todo el contenido del vault
      debug:
        var: bioinf_credentials
      run_once: true

    - name: Debug 2 - Mostrar IP del host actual
      debug:
        var: inventory_hostname
      run_once: true

    - name: Debug 3 - Verificar si existe la clave para este host
      debug:
        msg: "¿Existe la clave '{{ inventory_hostname.split(' - ')[1] }}'? {{ inventory_hostname.split(' - ')[1] in bioinf_credentials }}"
      run_once: true

    - name: Debug 4 - Mostrar todas las claves disponibles
      debug:
        msg: "Claves en vault: {{ bioinf_credentials.keys() | list }}"
      run_once: true
