# test_vault.yml
---
- name: Test conexión con vault
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Cargar vault manualmente
      include_vars:
        file: vault.yml
        name: bioinf_credentials

    - name: Cargar credenciales específicas para cada host
      set_fact:
        ansible_user: "{{ bioinf_credentials[inventory_hostname].user }}"
        ansible_ssh_pass: "{{ bioinf_credentials[inventory_hostname].password }}"
        ansible_become_pass: "{{ bioinf_credentials[inventory_hostname].password }}"

    - name: Probar conexión básica
      ansible.builtin.ping:
