- name: PRUEBA - Limpieza automática de /tmp con requeue
  hosts: all
  become: yes
  gather_facts: no
  vars:
    ansible_become_exe: "sudo -n"
    max_wait_minutes: 10
    check_interval_minutes: 2
    test_mode: true
    
  tasks:
    - name: Obtener hostname completo (como lo ve SLURM)
      shell: hostname -f
      register: hostname_full
      changed_when: false
      
    - name: Verificar jobs corriendo en SLURM
      shell: squeue -h -w {{ hostname_full.stdout }} -o "%i:%u:%j:%T:%N" 2>/dev/null
      register: running_jobs
      changed_when: false
      failed_when: false
      
    - name: Mostrar información del nodo
      debug:
        msg:
          - "Hostname corto: {{ hostname_full.stdout }}"
          - "Jobs encontrados: {{ running_jobs.stdout_lines }}"
          - "Número de jobs: {{ running_jobs.stdout_lines | length }}"
        
    - name: Verificar conexión con SLURM
      shell: which squeue && echo "SLURM disponible" || echo "SLURM no disponible"
      register: slurm_check
      changed_when: false
      
    - name: Mostrar estado de SLURM
      debug:
        msg: "Estado SLURM: {{ slurm_check.stdout }}"
        
    - name: Verificar nodo en SLURM
      shell: scontrol show node {{ hostname_full.stdout }} 2>/dev/null | head -5 || echo "Nodo no encontrado en SLURM"
      register: node_check
      changed_when: false
      
    - name: Mostrar información del nodo SLURM
      debug:
        msg: "Información SLURM: {{ node_check.stdout }}"
      
    - name: Listar TODOS los jobs en el cluster
      shell: squeue -o "%i:%j:%N:%T:%u" 2>/dev/null | head -10
      register: all_jobs
      changed_when: false
      
    - name: Mostrar todos los jobs
      debug:
        msg: "Todos los jobs en cluster: {{ all_jobs.stdout_lines }}"
