- name: PRUEBA - Limpieza automática de /tmp con requeue
  hosts: all # bioinfpre3.vhio.org
  become: yes
  gather_facts: no
  vars:
    ansible_become_exe: "sudo -n"
    max_wait_minutes: 10  # 10 minutos máximo para prueba
    check_interval_minutes: 2  # Verificación cada 2 minutos
    test_mode: true  # Modo prueba - no elimina archivos reales
    
  tasks:
    - name: Obtener nombre corto del host (como lo ve SLURM)
      shell: hostname -s
      register: hostname_short
      changed_when: false
      
    - name: Verificar jobs corriendo en SLURM
      shell: squeue -h -w {{ hostname_short.stdout }} -o "%i:%u:%j:%T:%N" 2>/dev/null
      register: running_jobs
      changed_when: false
      failed_when: false
      
    - name: Mostrar jobs encontrados
      debug:
        msg: "Jobs encontrados en {{ hostname_short.stdout }}: {{ running_jobs.stdout_lines }}"
        
    - name: Simular drain del nodo (modo prueba)
      debug:
        msg: "MODO PRUEBA: Simulando drain del nodo {{ hostname_short.stdout }}"
      when: running_jobs.stdout != ""
      
    - name: Esperar máximo 10 minutos para que terminen los jobs
      shell: squeue -h -w {{ hostname_short.stdout }} -o "%i:%u:%j:%T:%N" 2>/dev/null
      register: remaining_jobs
      until: remaining_jobs.stdout == ""
      retries: 5  # 5 intentos (10 minutos con delay de 2 minutos)
      delay: 120  # 120 segundos = 2 minutos
      when: running_jobs.stdout != ""
      
    - name: Mostrar estado final de la espera
      debug:
        msg: "Después de {{ max_wait_minutes }} minutos - Jobs pendientes: {{ remaining_jobs.stdout_lines }}"
      when: running_jobs.stdout != ""
      
    - name: Simular requeue de jobs pendientes
      debug:
        msg: "MODO PRUEBA: Simulando requeue de jobs {{ remaining_jobs.stdout_lines }}"
      when: 
        - running_jobs.stdout != ""
        - remaining_jobs.stdout != ""
      
    - name: Simular reactivación del nodo
      debug:
        msg: "MODO PRUEBA: Simulando reactivación del nodo {{ hostname_short.stdout }}"
      when: running_jobs.stdout != ""
      
    - name: Simular limpieza de /tmp (solo muestra)
      shell: |
        echo "MODO PRUEBA: Simulando limpieza de /tmp"
        find /tmp -type f -mtime +1 -name "*.tmp" 2>/dev/null | head -5 || true
      register: tmp_cleanup_simulation
      changed_when: false
      
    - name: Mostrar archivos que se eliminarían
      debug:
        msg: "Archivos antiguos encontrados: {{ tmp_cleanup_simulation.stdout_lines }}"
        
    - name: Resultado final de la prueba
      debug:
        msg:
          - "PRUEBA COMPLETADA en {{ hostname_short.stdout }}"
          - "Jobs encontrados inicialmente: {{ running_jobs.stdout_lines | length }}"
          - "Jobs pendientes al final: {{ remaining_jobs.stdout_lines | default([]) | length }}"
          - "Tiempo de espera: {{ max_wait_minutes }} minutos"
          - "MODO PRUEBA: No se ejecutaron comandos reales de SLURM"
