- name: Requeue automático CON CAMBIO DE NODO y control de /tmp
  hosts: all
  become: yes
  vars:
    ansible_become_exe: "sudo -n"
    tmp_size_limit_gb: 1  # Límite en GB para /tmp por usuario
    
  tasks:
    - name: Obtener hostname completo
      command: hostname -f
      register: hostname_full
      changed_when: false
      
    - name: Detectar usuarios con archivos grandes en /tmp
      shell: |
        du -sh /tmp/* 2>/dev/null | awk '{
          size=$1; path=$2;
          # Convertir tamaño a GB
          if (size ~ /G$/) {
            gsub(/G/, "", size);
            size_gb = size + 0;
          } else if (size ~ /M$/) {
            gsub(/M/, "", size);
            size_gb = size / 1024;
          } else if (size ~ /K$/) {
            gsub(/K/, "", size);
            size_gb = size / 1024 / 1024;
          } else {
            size_gb = size / 1024 / 1024 / 1024;
          }
          
          # Si supera el límite
          if (size_gb > {{ tmp_size_limit_gb }}) {
            # Extraer usuario del path
            split(path, parts, "/");
            for (i in parts) {
              if (parts[i] ~ /^[a-z]/) {
                print parts[i], size_gb;
                break;
              }
            }
          }
        }' | sort -u
      register: problematic_users
      changed_when: false
      failed_when: false
      
    - name: Mostrar usuarios problemáticos
      debug:
        msg: |
          "⚠️  Usuarios con uso excesivo de /tmp (>{{ tmp_size_limit_gb }}GB):"
          {% if problematic_users.stdout_lines | length > 0 %}
          {% for line in problematic_users.stdout_lines %}
          "  - {{ line }}"
          {% endfor %}
          {% else %}
          "  Ninguno detectado"
          {% endif %}
      
    - name: Encontrar nodo alternativo
      shell: |
        sinfo -p short -h -o "%N" | tr ',' '\n' | grep -v {{ hostname_full.stdout }} | grep -v down | head -1 || echo "NO_ALTERNATIVE"
      register: alternative_node
      changed_when: false
      failed_when: false
      
    - name: Verificar jobs en este nodo
      shell: |
        squeue -h -w {{ hostname_full.stdout }} -o "%i:%u:%j:%T:%N:%P" 2>/dev/null || echo "NO_JOBS"
      register: running_jobs
      changed_when: false
      failed_when: false
      
    - name: Mostrar estado actual
      debug:
        msg: |
          "Nodo actual: {{ hostname_full.stdout }}"
          "Nodo alternativo: {{ alternative_node.stdout }}"
          "Jobs encontrados: {{ running_jobs.stdout_lines if running_jobs.stdout != 'NO_JOBS' else 'NINGUNO' }}"
        
    - name: Salir si no hay jobs
      debug:
        msg: "✅ No hay jobs en {{ hostname_full.stdout }} - nada que hacer"
      when: running_jobs.stdout == "NO_JOBS" or running_jobs.stdout == ""
      
    - name: Continuar si hay jobs
      block:
        - name: Cancelar jobs de usuarios problemáticos
          shell: |
            {% if problematic_users.stdout_lines | length > 0 %}
            echo "🚫 Cancelando jobs de usuarios con /tmp excesivo..."
            {% for line in problematic_users.stdout_lines %}
            user=$(echo "{{ line }}" | awk '{print $1}')
            size=$(echo "{{ line }}" | awk '{print $2}')
            echo "  Cancelando jobs de $user (${size}GB en /tmp)"
            scancel -u $user -w {{ hostname_full.stdout }}
            {% endfor %}
            {% else %}
            echo "✅ No hay usuarios problemáticos - todos los jobs son elegibles"
            {% endif %}
          args:
            executable: /bin/bash
          register: cancel_result
          failed_when: false
          
        - name: Drainear nodo
          shell: |
            scontrol update NodeName={{ hostname_full.stdout }} State=DRAIN Reason="Auto-requeue to {{ alternative_node.stdout }}"
          register: drain_result
          failed_when: false
          
        - name: Esperar 15 segundos
          pause:
            seconds: 15
          
        - name: Requeuear jobs restantes con cambio de nodo
          shell: |
            # Crear lista de usuarios problemáticos
            problematic_users=""
            {% if problematic_users.stdout_lines | length > 0 %}
            {% for line in problematic_users.stdout_lines %}
            problematic_users="$problematic_users $(echo '{{ line }}' | awk '{print $1}')"
            {% endfor %}
            {% endif %}
            
            for jobline in $(squeue -h -w {{ hostname_full.stdout }} -o "%i:%u" 2>/dev/null); do
              jobid=$(echo $jobline | cut -d: -f1)
              jobuser=$(echo $jobline | cut -d: -f2)
              
              # Verificar si el usuario es problemático
              skip=0
              for puser in $problematic_users; do
                if [ "$jobuser" = "$puser" ]; then
                  echo "⏭️  Saltando job $jobid del usuario problemático $jobuser"
                  skip=1
                  break
                fi
              done
              
              if [ $skip -eq 0 ]; then
                echo "✅ Procesando job $jobid del usuario $jobuser"
                {% if alternative_node.stdout != "NO_ALTERNATIVE" %}
                  echo "  Moviendo job $jobid a {{ alternative_node.stdout }}"
                  scancel $jobid
                  sleep 2
                  scontrol show job $jobid | grep "Command=" | cut -d= -f2 | xargs sbatch --nodelist={{ alternative_node.stdout }}
                {% else %}
                  echo "  Requeue normal del job $jobid"
                  scontrol requeue $jobid
                {% endif %}
              fi
            done
          args:
            executable: /bin/bash
          register: requeue_result
          failed_when: false
          
        - name: Esperar 30 segundos
          pause:
            seconds: 30
          
        - name: Reactivar nodo
          shell: |
            scontrol update NodeName={{ hostname_full.stdout }} State=RESUME
          register: resume_result
          failed_when: false
          
        - name: Resultado final
          debug:
            msg:
              - "✅ REQUEUE COMPLETADO en {{ hostname_full.stdout }}"
              - "Jobs totales procesados: {{ running_jobs.stdout_lines | length }}"
              - "Usuarios problemáticos cancelados: {{ problematic_users.stdout_lines | length }}"
              - "Nodo destino: {{ alternative_node.stdout }}"
      when: running_jobs.stdout != "NO_JOBS" and running_jobs.stdout != ""
