- name: Requeue automático CON DEBUG
  hosts: bioinfpre3  # ⚠️ SOLO en el nodo que funciona
  become: yes
  vars:
    ansible_become_exe: "sudo -n"
    
  tasks:
    - name: Obtener hostname actual
      command: hostname -f
      register: hostname_full
      changed_when: false
      
    - name: Verificar TODOS los nodos disponibles
      shell: |
        sinfo -o "%N:%P:%T:%C" | grep -v DOWN
      register: all_nodes
      changed_when: false
      
    - name: Mostrar nodos disponibles
      debug:
        msg: "Nodos SLURM disponibles: {{ all_nodes.stdout_lines }}"
        
    - name: Verificar particiones
      shell: |
        sinfo -o "%P:%N:%T" | grep -v down
      register: partitions_info
      
    - name: Mostrar particiones
      debug:
        msg: "Particiones: {{ partitions_info.stdout_lines }}"
        
    - name: Verificar jobs en TODOS los nodos
      shell: |
        squeue -o "%i:%u:%j:%T:%N:%P:%b" | grep -E "(RUNNING|PENDING)"
      register: all_jobs
      
    - name: Mostrar todos los jobs
      debug:
        msg: "Jobs en cluster: {{ all_jobs.stdout_lines }}"
        
    - name: Verificar jobs en este nodo CON DETALLE
      shell: |
        squeue -w {{ hostname_full.stdout }} -o "%i:%u:%j:%T:%N:%P:%b" 2>/dev/null
      register: node_jobs_detail
      
    - name: Mostrar jobs con detalles
      debug:
        msg: "Jobs en {{ hostname_full.stdout }}: {{ node_jobs_detail.stdout_lines }}"
